### ISSUE TITLE
Typed "Really" with one letter "L" instead of two. 

### ISSUE THREAD

**Issue by LBrownI** [LBrownI/Evaluacion3_Equipo1#1]
In code: "realy", Line 31 of the following .py file:
https://github.com/LBrownI/Evaluacion3_Equipo1/blob/5e48d6e3c4e3ee9b6ff1446ce41a5ebd8c9a659a/main.py#L31C7-L31C7

**Comment by AlanSilvaaa** [comment]
typo fixed, check the [fix typo](https://github.com/LBrownI/Evaluacion3_Equipo1/commit/366d8b24801cdf5ec4d95d41944695400af59863) commit to see the changes.
